### ISSUE TITLE
Create custom 404 page

### ISSUE THREAD

**Issue by jsnmrs** [double-great/theme#12]
It should be very cool, ideally.

**Comment by jsnmrs** [comment]
@katydecorah Following up on this one — I'm seeing that [https://doublegreat.dev/theme/badlink](https://doublegreat.dev/theme/badlink) is not showing the custom 404 page that was created in #23.

It could be that 404.html isn't traveling with the theme, so the lack of an explicit 404 in the [primary repo](https://github.com/double-great/double-great.github.io) means there's not a 404 template at all.

Any ideas?

**Comment by katydecorah** [comment]
> It could be that 404.html isn't traveling with the theme, so the lack of an explicit 404 in the [primary repo](https://github.com/double-great/double-great.github.io) means there's not a 404 template at all.

I think that's exactly the problem, the 404 doesn't seem to want to travel with the theme.

**Comment by katydecorah** [comment]
Oh! We might be because we are missing a permalink on the page: https://jekyllrb.com/tutorials/custom-404-page/

I'll PR!
